export const ALL_SERVICE_REQUEST= "ALL_SERVICE_REQUEST";
export const ALL_SERVICE_SUCCESS= "ALL_SERVICE_SUCCESS";
export const ALL_SERVICE_FAIL= "ALL_SERVICE_FAIL";

export const CLEAR_ERRORS= "CLEAR_ERRORS";