export const ALL_SERVICE_REQUEST= "ALL_SERVICE_REQUEST";
export const ALL_SERVICE_SUCCESS= "ALL_SERVICE_SUCCESS";
export const ALL_SERVICE_FAIL= "ALL_SERVICE_FAIL";


export const SERVICE_DETAILS_REQUEST= "SERVICE_DETAILS_REQUEST";
export const SERVICE_DETAILS_SUCCESS= "SERVICE_DETAILS_SUCCESS";
export const SERVICE_DETAILS_FAIL= "SERVICE_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST="NEW_REWIEW_REQUEST";
export const NEW_REVIEW_SUCCESS="NEW_REWIEW_SUCCESS";
export const NEW_REVIEW_RESET="NEW_REWIEW_RESET";
export const NEW_REVIEW_FAIL="NEW_REWIEW_FAIL";

export const CLEAR_ERRORS= "CLEAR_ERRORS";