export const ALL_SERVICE_REQUEST= "ALL_SERVICE_REQUEST";
export const ALL_SERVICE_SUCCESS= "ALL_SERVICE_SUCCESS";
export const ALL_SERVICE_FAIL= "ALL_SERVICE_FAIL";


export const ADMIN_SERVICE_REQUEST= "ADMIN_SERVICE_REQUEST";
export const ADMIN_SERVICE_SUCCESS= "ADMIN_SERVICE_SUCCESS";
export const ADMIN_SERVICE_FAIL= "ADMIN_SERVICE_FAIL";


export const SERVICE_DETAILS_REQUEST= "SERVICE_DETAILS_REQUEST";
export const SERVICE_DETAILS_SUCCESS= "SERVICE_DETAILS_SUCCESS";
export const SERVICE_DETAILS_FAIL= "SERVICE_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST="NEW_REWIEW_REQUEST";
export const NEW_REVIEW_SUCCESS="NEW_REWIEW_SUCCESS";
export const NEW_REVIEW_RESET="NEW_REWIEW_RESET";
export const NEW_REVIEW_FAIL="NEW_REWIEW_FAIL";

export const DELETE_SERVICE_REQUEST= "DELETE_SERVICE_REQUEST";
export const DELETE_SERVICE_SUCCESS= "DELETE_SERVICE_SUCCESS";
export const DELETE_SERVICE_RESET="DELETE_SERVICE_RESET";
export const DELETE_SERVICE_FAIL= "DELETE_SERVICE_FAIL";


export const UPDATE_SERVICE_REQUEST= "UPDATE_SERVICE_REQUEST";
export const UPDATE_SERVICE_SUCCESS= "UPDATE_SERVICE_SUCCESS";
export const UPDATE_SERVICE_RESET="UPDATE_SERVICE_RESET";
export const UPDATE_SERVICE_FAIL= "UPDATE_SERVICE_FAIL";


export const NEW_SERVICE_REQUEST="NEW_SERVICE_REQUEST";
export const NEW_SERVICE_SUCCESS="NEW_SERVICE_SUCCESS";
export const NEW_SERVICE_RESET="NEW_SERVICE_RESET";
export const NEW_SERVICE_FAIL="NEW_SERVICE_FAIL";

export const ALL_REVIEW_REQUEST="ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS="ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL="ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST="DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS="DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET="DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL="DELETE_REVIEW_FAIL";



export const CLEAR_ERRORS= "CLEAR_ERRORS";